### ISSUE TITLE
Опечатка (?) в теор. дз №1

### ISSUE THREAD

**Issue by dsvishnev** [FilatovArtm/ML_Eco-NES_2017#1]
Что такое $x^T_i$ в задаче 5 (последняя строчка первой страницы) в аргументе экспоненты есть? Нет ли там опечатки?

Спасибо! 

P.S. Кстати, как лучше задавать такие вопросы? Здесь или в телеграмме/еще как-то?

**Comment by FilatovArtm** [comment]
Это какой-то вектор, транспонированный. Такой, что произведение на вектор \beta корректно определено. А что смущает? Вопросы лучше задавать в чате.

**Comment by bdemeshev** [comment]
Если вопрос на понимание "А что это?" — то, конечно, в чате. А если есть чёткое понимание, которое рождает подозрение, что в тексте опечатка, то здесь, т.к. это тогда подозрение на баг, который надо описывать с помощью issue. Закрываю :)
